# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginwithemailandpwd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginwithemailandpwd(self):
    # Test name: Login with email and pwd
    # Step # | name | target | value
    # 1 | open | https://gamma.app/signin | 
    self.driver.get("https://gamma.app/signin")
    # 2 | setWindowSize | 2560x1342 | 
    self.driver.set_window_size(2560, 1342)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | sean.ulric.chua@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("sean.ulric.chua@gmail.com")
    # 5 | type | id=password | ThunderLightning12#
    self.driver.find_element(By.ID, "password").send_keys("ThunderLightning12#")
    # 6 | click | xpath=//button[contains(., "Sign in")] | 
    self.driver.find_element(By.XPATH, "//button[contains(., \"Sign in\")]").click()
  
